# Generated by Django 4.1.1 on 2022-09-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_collection_movies_movie_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.collection'),
            preserve_default=False,
        ),
    ]
