# Generated by Django 4.1.1 on 2022-09-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='id',
            new_name='uuid',
        ),
    ]
