# Generated by Django 4.1.1 on 2022-09-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api.collection'),
        ),
    ]
