# Generated by Django 4.1.1 on 2022-09-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_collection_moview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='moview',
            new_name='movies',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
