# Generated by Django 4.1.1 on 2022-09-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_moview_collection_movies_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='genres',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
